### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by katichka87** [SiliconValleyInsight/activity_tracker#13]
@ianjrinon,
Please recheck font sizes. 106sp is too big ))

![screenshot_2015-08-11-00-32-48](https://cloud.githubusercontent.com/assets/11774085/9184913/daebfae8-3fc0-11e5-840b-7ea54f6d42a0.png)

**Comment by mavieungco** [comment]
Hi @katichka87 Ian says he sent the revised specs? Can I close this issue?
