### ISSUE TITLE
User Story: User should be able to edit/correct recorded activity 

### ISSUE THREAD

**Issue by mavieungco** [SiliconValleyInsight/activity_tracker#20]
From daily log/activity screen, user should be able to select an activity that may have been erroneously recorded (example: activity recorded as Biking but should really be In Vehicle). 

Flow:
 
Daily Log > Click on Activity > Activity Screen > Click on Edit Activity icon (pencil icon at the upper right corner of the screen) > Edit Activity popup with drop down menu > Select correct activity from drop down menu > Click on Done button > Changes should be reflected on the Activity Screen and on the Daily Log screen 

![activity](https://cloud.githubusercontent.com/assets/12859869/9242195/6e4a687e-41b0-11e5-8301-1dc06f8be006.png)

![activityfeeds_popup](https://cloud.githubusercontent.com/assets/12859869/9242198/743eee08-41b0-11e5-8fcc-c51c8c6ec973.png)

![activityfeeds_popup_expanded](https://cloud.githubusercontent.com/assets/12859869/9242200/78afe60e-41b0-11e5-8648-944d75b08232.png)

**Comment by dualcnhq** [comment]
as discussed will be doing this in Phase 2 so we could focus on tracking first.

**Comment by mavieungco** [comment]
Since this is not implementable with the current API, closing this issue now.
