### ISSUE TITLE
Check what we can track on different devices

### ISSUE THREAD

**Issue by katichka87** [SiliconValleyInsight/activity_tracker#3]
Hi all, I added code that will show activity summary for the activities that device can track. If you have some devices with different kinds of sensors, please test the latest code with them, if something else besides "walking" and "in vehicle" appears in the list.
Thanks you

cc @dualcnhq , @mavieungco , @JohnYangSam , @ianjrinon

**Comment by dualcnhq** [comment]
@katichka87 still showing "Walking" and "In Vehicle" activities.

some activity like "In Vehicle" is not accurate during a specific time.
also checked returned results from Google Fit app, it shows different data compare to our current build.

**Comment by katichka87** [comment]
@dualcnhq , can you put here the screenshots of google fit and our app activities list for comparing?

By the way, I also succeed to track cycling today. But it was also interpreted as walking activity.

![screenshot_2015-08-04-10-20-18](https://cloud.githubusercontent.com/assets/11774085/9055396/7d5c0f30-3a93-11e5-92b1-c93b352a8a3a.png)

**Comment by mavieungco** [comment]
Closing this issue.
