### ISSUE TITLE
Icons Inquiry

### ISSUE THREAD

**Issue by ianjrinon** [SiliconValleyInsight/activity_tracker#30]
Some of the icons are small...do I need to adjust the icons?

![screenshot_2015-08-18-16-07-09](https://cloud.githubusercontent.com/assets/13011461/9326113/0c069084-45ca-11e5-8b46-4a6f9af5143b.png)

**Comment by dualcnhq** [comment]
@ianjrinon it's probably in the layout, will update it

**Comment by mavieungco** [comment]
Can I close this issue @dualcnhq @ianjrinon? This problem doesn't appear anymore from my end.

**Comment by mavieungco** [comment]
Closing this.
