### ISSUE TITLE
Activities Log screen does not display other details other than duration and time 

### ISSUE THREAD

**Issue by mavieungco** [SiliconValleyInsight/activity_tracker#34]
In the activities log screen, right below the activity label (In Vehicle, Waking, Biking), other info should be displayed such as time, location, distance, speed. 

See iteration 7 folder in the project folder: https://drive.google.com/drive/u/0/folders/0B7mwq2WyUQ7_flJwOFpxV1lTUG9YVFA5eVJQWU9QeXdsOW4xc19PeXZqWF9TNUdockcxWXc

**Comment by dualcnhq** [comment]
@katichka87 i added the icons and textview here, kindly change the values instead, thanks

**Comment by mavieungco** [comment]
@dualcnhq can I close this issue?

**Comment by mavieungco** [comment]
Closing this issue.
