### ISSUE TITLE
If distance is less than 1 km, can it be displayed in metres? 

### ISSUE THREAD

**Issue by mavieungco** [SiliconValleyInsight/activity_tracker#35]
In one activity of mine tracked by the app, the distance is displayed as 0.0086701205 km. 

Seems too long. If distance is less than 1 km, can we display the value in metres so it's not a lot of numbers after the decimal point? 

![screenshot_2015-08-20-11-53-07](https://cloud.githubusercontent.com/assets/12859869/9375351/28d5f916-4732-11e5-8180-f1972e7a5acc.jpg)

**Comment by dualcnhq** [comment]
@katichka87 can i assign this to you?

**Comment by mavieungco** [comment]
Closing this issue.
