### ISSUE TITLE
Activity screen: time format displays only 0:0 instead of 0:00

### ISSUE THREAD

**Issue by mavieungco** [SiliconValleyInsight/activity_tracker#41]
Please see screenshot. 

![screenshot_2015-08-20-11-38-56](https://cloud.githubusercontent.com/assets/12859869/9375196/6314244c-4730-11e5-92ef-9aea8ad4d007.jpg)

**Comment by dualcnhq** [comment]
assigning this issue to @katichka87

**Comment by mavieungco** [comment]
Closing this issue.
