### ISSUE TITLE
Speed, location, distance values on list sreen

### ISSUE THREAD

**Issue by katichka87** [SiliconValleyInsight/activity_tracker#45]
Extracting the values of location, speed and distance for the whole list requires long running operations.
My suggestion is to display them just on the detail screen

![screenshot_2015-08-20-21-41-41](https://cloud.githubusercontent.com/assets/11774085/9392449/6a418f2a-4785-11e5-9441-24d872972ada.png)

**Comment by dualcnhq** [comment]
@katichka87 i agree to that, though it's in the mockup/design @ianjrinon made.
so maybe we could consider doing that in the detail instead, what do you think @mavieungco @JohnYangSam

**Comment by JohnYangSam** [comment]
OK. To just put in detail screen. Curious what long operation we need. Are we not storing that data already or are we just pulling from the api?

**Comment by katichka87** [comment]
@JohnYangSam ,
We need to request it from API for each time interval. And after that request city name for each location
